PRO-16890 : Enforce required flags for provar:metadatacache
ProvarTesting/provardx pull request #26
Opened 2020-08-25 13:43 UTC by MayankNehru

The command started executing even when required flags were not given. Changed that to give error in typescript itself. Also made changes to make sure that the flags work correctly in tandem.

2020-08-26 07:09 UTC, riteshnahar requested changes
Please do necessary changes in `CHANGELOG.md` file as well

2020-08-26 07:09 UTC, riteshnahar commented on src/commands/provar/metadatacache.ts
> +        if (
Change it to:
`if (!["Reload", "Refresh", "Reuse"].includes(metadataLevel))`

2020-08-26 07:09 UTC, riteshnahar commented on src/commands/provar/metadatacache.ts
> +        const userInfoString = connections && userInfo == null ? "NA" : provarDxUtils.prepareRawProperties(
`userInfo === null`

2020-08-28 08:53 UTC, riteshnahar approved these changes

2020-08-28 09:46 UTC, simoncarter-provar requested changes

2020-08-28 09:46 UTC, simoncarter-provar commented on src/commands/provar/metadatacache.ts
> +        (!["Reload", "Refresh", "Reuse"].includes(metadataLevel)) {
Should this be an if statement?

`if (!["Reload", "Refresh", "Reuse"].includes(metadataLevel)) {`

2020-08-28 10:37 UTC, simoncarter-provar approved these changes

2020-08-28 11:47 UTC, merged